"""
Report Builder — LangGraph node.

Assembles the final ViolationReport from state, computing summary statistics
and an overall compliance status.

Writes violation_report to state.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "none": 4}


def report_builder_node(state: dict) -> dict:
    """
    LangGraph node: assemble the ViolationReport dict.

    Always runs — even when there's an error — so callers always get
    a well-formed response.
    """
    error = state.get("error")
    violations = state.get("violations", [])
    document_name = state.get("document_name", "unknown")

    # Sort violations: critical first, then high, medium, low
    violations_sorted = sorted(
        violations,
        key=lambda v: _SEVERITY_ORDER.get(v.get("severity", "low"), 4),
    )

    # Summary counts
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for v in violations_sorted:
        sev = v.get("severity", "low")
        if sev in severity_counts:
            severity_counts[sev] += 1

    # Overall compliance determination
    if error and not violations_sorted:
        overall_status = "error"
    elif severity_counts["critical"] > 0:
        overall_status = "non_compliant"
    elif severity_counts["high"] > 0:
        overall_status = "non_compliant"
    elif severity_counts["medium"] > 0 or severity_counts["low"] > 0:
        overall_status = "partially_compliant"
    else:
        overall_status = "compliant"

    report = {
        "document_name": document_name,
        "overall_status": overall_status,
        "total_violations": len(violations_sorted),
        "severity_summary": severity_counts,
        "violations": violations_sorted,
        "analyzed_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": (
            "This analysis is generated by an AI system and is for informational purposes only. "
            "It does not constitute legal or regulatory advice. Consult a qualified regulatory "
            "professional before making compliance decisions."
        ),
        "error": error,
    }

    logger.info(
        "Report built for '%s': status=%s, violations=%d",
        document_name,
        overall_status,
        len(violations_sorted),
    )
    return {"violation_report": report}
